### ISSUE TITLE
WebUI to show drone progress, with button to take you to chatbot

### ISSUE THREAD

**Issue by Laura7089** [2023-gpig-a/frontend#5]

**Comment by BabarKhanDev** [comment]
What we want is:
1. frontend calls dronemanager/drone_status. This returns an array of drones, call this []d
2. for each drone d, get d.lastSeen, this is a latlong. Call dmas/track_growth/?center=[lat,long]&scan_range=drone_vision&day_range=1
3. This will return a json file with plant growth data, this contains an array of species:datum mappings. you want to go through each datum and put a little image of this plant on the map. This should only return roses and knotweed so we just need two symbols. These images should stay on the map even when we rescan. 

One note of caution, we don't want to show the same plant on the map multiple times. Maybe we could store all of the returned datums in a set and then show that set every time we redraw it.
